### ISSUE TITLE
No graph on the page

### ISSUE THREAD

**Issue by chut211** [DawnPaladin/Argdown#3]
Description of the problem:
With the example
[statement]: I am a statement. #tag1
 <- argument 1>
 + <argument 2>
    <_ <argument 3>
there is no graph.
When I edit the page I can see "<> Ardown" and when I click on it the code of the example is shown and can be modified

Conf:
MediaWiki | 1.35.1
PHP | 7.4.16 (apache2handler)
MySQL | 8.0.23-0ubuntu0.20.04.1
Lua | 5.1.5

**Comment by toasty-sunbeam** [comment]
Hello! Here are a few troubleshooting steps to follow.

1. Have you put `<argdown>` before your argument and `</argdown>` after it?
2. What version of Node are you running?
3. Have you tried setting `$wgMaxShellMemory = 0;` in LocalSettings.php, as described in [the setup instructions](https://github.com/DawnPaladin/Argdown-for-MediaWiki#setup)?

**Comment by chut211** [comment]
Hello,

Thx for the process:
1. OK
2. OK but there were two versions of node ==> I deleted the old one: OK
3. OK

It works perfectly, Thank you very much
