### ISSUE TITLE
All arguments's boxes are green and not red

### ISSUE THREAD

**Issue by chut211** [DawnPaladin/Argdown#4]
Hello,

May I ask you another question.
My attacking arguments are in green box, and not in red ones.
Is there something to do, to check ?

versions: nodejs: 14.16.0
Is it a question of:
- skin in mediawiki
- svg (need to be installed)

Thank you for your help
![Argdown](https://user-images.githubusercontent.com/15700287/111000793-ff786700-8382-11eb-94c7-ac18f6b325ca.PNG)

**Comment by toasty-sunbeam** [comment]
That's the way Argdown sets things up by default. To change the color of your boxes, see this page: https://argdown.org/guide/colorizing-maps.html

**Comment by chut211** [comment]
"RTFM"! ;-)
Thank you very much
